.TH ld.so.conf 5 (date) "Linux man-pages (unreleased)"
.SH NAME
ld.so.conf \- ld.so configuration file
.SH SYNOPSIS
.nf
.B /etc/ld.so.conf
.fi
.SH DESCRIPTION
This file contains a list of directories,
one per line,
in which to search for libraries.
.SH FILES
.I /etc/ld.so.conf
.SH SEE ALSO
.BR ld.so (8),
.BR ldconfig (8)
