'\" t
.\" Copyright 2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH bzero 3 (date) "Linux man-pages (unreleased)"
.SH NAME
bzero \- byte-array zero
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.BR #include\~<strings.h> "  // see memory.h(3head)"
.P
.BR "void bzero(" "size_t n;"
.BI "           void " a [ n "], size_t " n );
.fi
.SH DESCRIPTION
This function
writes zeros (\[aq]\[rs]0\[aq])
to the memory starting at the location pointed to by
.IR a .
.P
It is equivalent to
.P
.in +4n
.EX
memset(a, \[aq]\[rs]0\[aq], n)
.EE
.in
.SH RETURN VALUE
None.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR bzero ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
None.
.SH HISTORY
4.3BSD.
.P
Marked as LEGACY in POSIX.1-2001.
Removed in POSIX.1-2008.
.SH SEE ALSO
.BR bstring (3),
.BR memory.h (3head),
.BR explicit_zero (3),
.BR memset (3)
