'\" t
.\" Copyright 1993, David Metcalfe <david@prism.demon.co.uk>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH strchr 3 (date) "Linux man-pages (unreleased)"
.SH NAME
strchr \- string search character
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.B #include <string.h>
.P
.BI "char *strchr(const char *" s ", int " c );
.fi
.SH DESCRIPTION
.BR strchr ()
returns a pointer to the first occurrence
of the character
.I c
in the string
.IR s .
.P
It is equivalent to both of the following expressions:
.P
.in +4n
.EX
memchr(s, c, strlen(s) + 1)
strpbrk(s, (char [2]){c, \[aq]\[rs]0\[aq]})
.EE
.in
.SH RETURN VALUE
.BR strchr ()
returns a pointer to
the matched character or NULL if the character is not found.
.P
The terminating null byte is considered part of the string,
so that if
.I c
is specified as \[aq]\[rs]0\[aq],
.BR strchr ()
returns a pointer to the terminator.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR strchr ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
C11, POSIX.1-2008.
.SH HISTORY
POSIX.1-2001, C89, SVr4, 4.3BSD.
.SH SEE ALSO
.BR memchr (3),
.BR string (3),
.BR strchrnul (3),
.BR strlen (3),
.BR strnul (3),
.BR strpbrk (3),
.BR strrchr (3),
.BR strsep (3),
.BR strspn (3),
.BR strstr (3),
.BR strtok (3),
.BR wcschr (3),
.BR wcsrchr (3)
