'\" t
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH streq 3 (date) "Linux man-pages (unreleased)"
.SH NAME
streq \- strings equal
.SH LIBRARY
gnulib \- The GNU Portability Library
.SH SYNOPSIS
.nf
.B #include <string.h>
.P
.BI "bool streq(const char *" s1 ", const char *" s2 );
.fi
.SH DESCRIPTION
.BR streq ()
determines whether the strings
.I s1
and
.I s2
are equal.
.P
It is equivalent to both of the following expressions:
.P
.in +4n
.EX
strcmp(s1, s2) == 0
memeq(s1, s2, MIN(strlen(s1),strlen(s2))+1)
.EE
.in
.SH RETURN VALUE
.BR streq ()
returns true if and only if the strings
.I s1
and
.I s2
are equal.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR streq ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
GNU.
.SH HISTORY
gnulib 202601.
.SH SEE ALSO
.BR string (3)
