.\" Copyright 1993, David Metcalfe <david@prism.demon.co.uk>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH string 3 (date) "Linux man-pages (unreleased)"
.SH NAME
string \- string operations
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.B #include <string.h>
.B #include <strings.h>
.fi
.SH DESCRIPTION
.SS Copy
.TP
.BR strcpy (3)
.TQ
.BR stpcpy (3)
.SS Catenate
.TP
.BR strcat (3)
.SS Duplicate
.TP
.BR strdup (3)
.TQ
.BR strdupa (3)
.SS Compare
.TP
.BR memeq (3)
This function should be in
.IR <memory.h> .
.TP
.BR streq (3)
.TQ
.BR strcmp (3)
.TQ
.BR strcasecmp (3)
.TQ
.BR strcoll (3)
.TQ
.BR strverscmp (3)
.SS Search
.TP
.BR strlen (3)
.TQ
.BR strnul (3)
.TQ
.BR strchrnul (3)
.TQ
.BR strchr (3)
.TQ
.BR strrchr (3)
.TQ
.BR strpbrk (3)
.TQ
.BR strstr (3)
.TQ
.BR strcasestr (3)
.TQ
.BR strspn (3)
.TQ
.BR strcspn (3)
.SS Separate
.TP
.BR strsep (3)
.TQ
.BR strtok (3)
.SS Others
.TP
.BR strxfrm (3)
.SH SEE ALSO
.BR memory.h (3head),
.BR string_copying (7)
