'\" t
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH strncat 3 (date) "Linux man-pages (unreleased)"
.SH NAME
strncat \- nonstring catenate
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.BR #include\~<memory.h> "  // See STANDARDS"
.P
.BR "char *strncat(" "size_t ssize;"
.BI "              char *restrict " dst ", const char " src "[restrict " ssize ],
.BI "              size_t " ssize );
.fi
.SH DESCRIPTION
This function appends at most
.I ssize
non-null bytes from the array pointed to by
.IR src ,
followed by a null character,
to the end of the string pointed to by
.IR dst .
.I dst
must point to a string contained in a buffer that is large enough,
that is, the buffer size must be at least
.IR "strlen(dst) + strnlen(src, ssize) + 1" .
.P
It is equivalent to
.P
.in +4n
.EX
stpcpy(mempcpy(strnul(dst), src, strnlen(src, ssize)), ""), dst
.EE
.in
.SH RETURN VALUE
.BR strncat ()
returns
.IR dst .
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR strncat ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
C11, POSIX.1-2008.
.P
ISO C and POSIX declare this function in
.IR <string.h> ;
see
.BR memory.h (3head).
.SH HISTORY
POSIX.1-2001, C89, SVr4, 4.3BSD.
.SH CAVEATS
The name of this function is confusing;
it has no relation to
.BR strncpy (3).
.P
If the destination buffer does not already contain a string,
or is not large enough,
the behavior is undefined.
See
.B _FORTIFY_SOURCE
in
.BR feature_test_macros (7).
.SH EXAMPLES
.\" SRC BEGIN (strncat.c)
.EX
#include <stdcountof.h>
#include <stdio.h>
#include <string.h>
#include <utmp.h>
\&
void print_ut_user(struct utmp *ut);
\&
void
print_ut_user(struct utmp *ut)
{
	char  buf[countof(ut\->ut_user) + 1];
\&
	strcpy(buf, "");
	strncat(buf, ut\->ut_user, countof(ut\->ut_user));
	puts(buf);
}
.EE
.\" SRC END
.in
.SH SEE ALSO
.BR memory.h (3head),
.BR string_copying (7)
