'\" t
.\" Copyright 1993, David Metcalfe <david@prism.demon.co.uk>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH strrchr 3 (date) "Linux man-pages (unreleased)"
.SH NAME
strrchr \- string rear-search character
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.B #include <string.h>
.P
.BI "char *strrchr(const char *" s ", int " c );
.fi
.SH DESCRIPTION
.BR strrchr ()
returns a pointer to the last occurrence
of the character
.I c
in the string
.IR s .
.P
It is equivalent to
.P
.in +4n
.EX
memrchr(s, c, strlen(s) + 1)
.EE
.in
.SH RETURN VALUE
See
.BR strchr (3).
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR strrchr ()
T}	Thread safety	MT-Safe
.TE
.SH STANDARDS
C11, POSIX.1-2008.
.SH HISTORY
POSIX.1-2001, C89, SVr4, 4.3BSD.
.SH SEE ALSO
.BR string (3),
.BR strchr (3),
.BR wcsrchr (3)
