.\" Copyright 2006, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-2.0-or-later
.\"
.TH standards 7 (date) "Linux man-pages (unreleased)"
.SH NAME
standards \- C and UNIX Standards
.SH DESCRIPTION
The STANDARDS section that appears in many manual pages identifies
various standards to which the documented interface conforms.
The following list briefly describes these standards.
.SS Research Unix
.TP
.B V7
Version 7 (also known as Seventh Edition) UNIX,
released by AT&T/Bell Labs in 1979.
After this point, UNIX systems diverged into two main dialects:
BSD and System V.
Sources are
.UR https:\://www.tuhs.org/\:cgi\-bin/\:utree.pl?file=V7
available online
.UE .
.SS BSD
.TP
.B 4.2BSD
This is an implementation standard defined by the 4.2 release
of the
.IR "Berkeley Software Distribution",
released by the University of California at Berkeley.
This was the first Berkeley release that contained a TCP/IP
stack and the sockets API.
4.2BSD was released in 1983.
Sources are
.UR https:\://www.tuhs.org/\:cgi\-bin/\:utree.pl?file=4.2BSD
available online
.UE .
.IP
Earlier major BSD releases included
.I 3BSD
(1980),
.I 4BSD
(1980),
and
.I 4.1BSD
(1981).
.TP
.B 4.3BSD
The successor to 4.2BSD, released in 1986.
Sources are
.UR https:\://www.tuhs.org/\:cgi\-bin/\:utree.pl?file=4.3BSD
available online
.UE .
.TP
.B 4.4BSD
The successor to 4.3BSD, released in 1993.
This was the last major Berkeley release.
Sources are
.UR https:\://www.tuhs.org/\:cgi\-bin/\:utree.pl?file=4.4BSD
available online
.UE .
.SS Unix/TS
.TP
.B Unix/TS 4
This was an internal release of Unix
that was never released to the public
(in which case it would have been called System IV).
The previous major AT&T release was
.IR "System III" ,
released in 1981.
.TP
.B System V (SVr1)
This is an implementation standard defined by AT&T's milestone 1983
release of its commercial System V (five) release.
.TP
.B System V release 2 (SVr2)
This was the next System V release, made in 1985.
The SVr2 was formally described in the
.I "System V Interface Definition Issue 1"
.RI ( "SVID 1" )
published in 1985.
.TP
.B System V release 3 (SVr3)
This was the successor to SVr2, released in 1986.
This release was formally described in the
.UR https:\://bitsavers.org/\:pdf/\:att/\:unix/\:SVID/\:System_V_Interface_Definition_Issue_2_Volume_1_1986.pdf
.I "System V Interface Definition Issue 2"
.RI ( "SVID 2" )
.UE .
.TP
.B System V release 4 (SVr4)
This was the successor to SVr3, released in 1989.
This version of System V is described in the "Programmer's Reference
Manual: Operating System API (Intel processors)" (Prentice-Hall
1992, ISBN 0-13-951294-2)
This release was formally described in the
.UR https:\://archive.org/\:details/\:systemvinterface0001unse/
.I "System V Interface Definition Third Edition"
.RI ( "SVID 3" )
.UE ,
and is considered the definitive System V release.
.TP
.B SVID 4
System V Interface Definition version 4, issued in 1995.
Available online at
.UR http:\://www.sco.com\:/developers\:/devspecs/
.UE .
.SS Standard C
.TP
.B K&R
This refers to the C language as specified in
.I \[lq]The C Programming Language\[rq]
[Brian W.\& Kernighan and Dennis M.\& Ritchie;
Prentice Hall;
1st Ed., 1978].
.TP
.B C89
This was the first C language standard, ratified by ANSI
(American National Standards Institute) in 1989
.RI ( X3.159-1989 ).
Sometimes this is known as
.IR "ANSI C" ,
but since C99 is also an
ANSI standard, this term is ambiguous.
It is
.UR https:\://nvlpubs.nist.gov/\:nistpubs/\:Legacy/\:FIPS/\:fipspub160.pdf
available online
.UE .
.IP
The rationale for the C89 standard is also
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:C89Rationale.pdf
available online
.UE .
.IP
This standard was also ratified by
ISO (International Standards Organization)
and IEC (International Electrotechnical Commision)
in 1990
.RI ( ISO/IEC\~9899:1990 ),
and is thus occasionally referred to as
.IR ISO\~C90 .
.TP
.B C94
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:tc1.htm
Technical Corrigendum 1
.UE
of C90 was ratified by ISO/IEC in 1994
.RI ( ISO/IEC\~9899:1990/Cor1:1994 ).
.TP
.B C95
This amendment of the C language standard was ratified by ISO/IEC in 1995
.RI ( ISO/IEC\~9899:1990/Amd1:1995 ).
A draft is
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:n412.pdf
available online
.UE .
.IP
The primary change in C95 was support for international character sets.
.TP
.B C96
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:tc2.htm
Technical Corrigendum 2
.UE
of C90 was ratified by ISO/IEC in 1996
.RI ( ISO/IEC\~9899:1990/Cor2:1996 ).
A draft is
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:n457.pdf
available online
.UE .
.TP
.B C99
This revision of the C language standard was ratified by ISO/IEC in 1999
.RI ( ISO/IEC\~9899:1999 ).
.IP
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:9899tc1/\:n32071.PDF
Technical Corrigendum 1
.UE
of C99 was ratified by ISO/IEC in 2001
.RI ( ISO/IEC\~9899:1999/Cor1:2001 ).
.IP
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:9899\-1999_cor_2\-2004.pdf
Technical Corrigendum 2
.UE
of C99 was ratified by ISO/IEC in 2004
.RI ( ISO/IEC\~9899:1999/Cor2:2004 ).
.IP
.UR https:\://www.open\-std.org/\:JTC1/\:SC22/\:WG14/\:www/\:docs/\:n1235.pdf
Technical Corrigendum 3
.UE
of C99 was ratified by ISO/IEC in 2007
.RI ( ISO/IEC\~9899:1999/Cor3:2007 ).
A draft is
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:n1256.pdf
available online
.UE .
.IP
The rationale for the C99 standard is also
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:C99RationaleV5.10.pdf
available online
.UE .
.TP
.B C11
This revision of the C language standard was ratified by ISO/IEC in 2011
.RI ( ISO/IEC\~9899:2011 ).
A draft is
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:n1570.pdf
available online
.UE .
.IP
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:n1606.pdf
Technical Corrigendum 1
.UE
of C11 was ratified by ISO/IEC in 2012
.RI ( ISO/IEC\~9899:2011/Cor1:2012 ).
.TP
.B C17
This revision of the C language standard was ratified by ISO/IEC in 2018
.RI ( ISO/IEC\~9899:2018 ).
A draft is
.UR https:\://web.archive.org/\:web/\:20181230041359if_/\:http:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:abq/\:c17_updated_proposed_fdis.pdf
available online
.UE .
.TP
.B C23
This revision of the C language standard was ratified by ISO/IEC in 2024
.RI ( ISO/IEC\~9899:2024 ).
A draft is
.UR https:\://www.open\-std.org/\:jtc1/\:sc22/\:wg14/\:www/\:docs/\:n3220.pdf
available online
.UE .
.SS POSIX and SUS
.TP
.B POSIX.1-1988
This was the first POSIX standard,
ratified by IEEE in 1998
.RI ( IEEE\~Std\~1003.1-1988 ).
The term "POSIX" was coined by Richard Stallman.
It is
.UR https:\://nvlpubs.nist.gov/\:nistpubs/\:Legacy/\:FIPS/\:fipspub151\-1.pdf
available online
.UE .
.TP
.B POSIX.1-1990
Part 1,
"Portable Operating System Interface for Computing Environments".
Ratified by IEEE in 1990,
.RI ( IEEE\~Std\~1003.1-1990 ),
and ratified by ISO/IEC in 1990
.RI ( ISO/IEC\~9945-1:1990 ).
It is
.UR https:\://nvlpubs.nist.gov/\:nistpubs/\:Legacy/\:FIPS/\:fipspub151\-2.pdf
available online
.UE .
.TP
.B POSIX.2
Part 2,
which describes commands and utilities.
Ratified by IEEE in 1992
.RI ( IEEE\~Std\~1003.2-1992 ),
and ratified by ISO/IEC in 1993
.RI ( ISO/IEC\~9945-2:1993 ).
.TP
.BR POSIX.1b " (formerly known as \f[I]POSIX.4\f[])"
Part 1b,
which describes real-time facilities for portable operating systems.
Ratified by IEEE in 1993
.RI ( IEEE\~Std\~1003.1b-1993 ).
.TP
.BR POSIX.1c " (formerly known as \f[I]POSIX.4a\f[])"
Part 1c,
which describes the POSIX threads interfaces.
Ratified by IEEE in 1995
.RI ( IEEE\~Std\~1003.1c-1995 ).
.TP
.B POSIX.1d
Part 1d,
which describes additional real-time extensions.
Ratified by IEEE in 1999
.RI ( IEEE\~Std\~1003.1d-1999 ).
.TP
.B POSIX.1g
Part 1g,
which describes networking APIs (including sockets).
Ratified by IEEE in 2000
.RI ( IEEE\~Std\~1003.1g-2000 ).
.TP
.B POSIX.1j
Part 1j,
which describes advanced real-time extensions.
Ratified by IEEE in 2000
.RI ( IEEE\~Std\~1003.1j-2000 ).
.TP
.B POSIX.1-1996
A revision of POSIX.1 which incorporated POSIX.1b and POSIX.1c.
Ratified by ISO/IEC in 1996
.RI ( ISO/IEC\~9945-1:1996 ).
.TP
.B XPG3
Released in 1989, this was the first release of the X/Open
Portability Guide to be based on a POSIX standard (POSIX.1-1988).
It is also known as
.IR Issue\~3 .
This multivolume guide was developed by the X/Open Group,
a multivendor consortium.
.TP
.B XPG4
A revision of the X/Open Portability Guide, released in 1992.
It is also known as
.IR Issue\~4 .
This revision incorporated POSIX.2.
.TP
.B XPG4v2
A 1994 revision of XPG4.
This is also referred to as
.IR Spec\~1170 ,
where 1170 referred to the number of interfaces
defined by this standard.
.TP
.B SUS\~(SUSv1)
Single UNIX Specification.
This was a repackaging of XPG4v2 and other X/Open standards
(X/Open Curses Issue 4 version 2,
X/Open Networking Service (XNS) Issue 4).
Systems conforming to this standard can be branded
.IR UNIX\~95 .
.TP
.B SUSv2
Single UNIX Specification version 2.
Sometimes also referred to as
.IR Issue\~5 .
This standard appeared in 1997.
Systems conforming to this standard can be branded
.IR UNIX\~98 .
See also
.UR http:\://www.unix.org\:/version2/
.UE .)
.TP
.B POSIX.1-2001
.TQ
.B SUSv3
This was a 2001 revision and consolidation of the
POSIX.1, POSIX.2, and SUS standards into a single document,
conducted under the auspices of the Austin Group
.UR http:\://www.opengroup.org\:/austin/
.UE .
The standard is available online at
.UR http:\://www.unix.org\:/version3/
.UE .
.IP
The standard defines two levels of conformance:
.IR "POSIX conformance" ,
which is a baseline set of interfaces required of a conforming system;
and
.IR "XSI Conformance",
which additionally mandates a set of interfaces
(the "XSI extension") which are only optional for POSIX conformance.
XSI-conformant systems can be branded
.IR UNIX\~03 .
.IP
The POSIX.1-2001 document is broken into four parts:
.IP
.BR XBD :
Definitions, terms, and concepts, header file specifications.
.IP
.BR XSH :
Specifications of functions (i.e., system calls and library
functions in actual implementations).
.IP
.BR XCU :
Specifications of commands and utilities
(i.e., the area formerly described by POSIX.2).
.IP
.BR XRAT :
Informative text on the other parts of the standard.
.IP
POSIX.1-2001 is aligned with C99, so that all of the
library functions standardized in C99 are also
standardized in POSIX.1-2001.
.IP
The Single UNIX Specification version 3 (SUSv3) comprises the
Base Specifications containing XBD, XSH, XCU, and XRAT as above,
plus X/Open Curses Issue 4 version 2 as an extra volume that is
not in POSIX.1-2001.
.TP
.B POSIX.1-2001 2002 edition
Technical Corrigendum 1
of POSIX.1-2001
was ratified by IEEE in 2002
.RI ( IEEE\~Std\~1003.1-2001/Cor1-2002 ).
.IP
This is informally known as
.IR POSIX.1-2002 .
.TP
.B POSIX.1-2001 2004 edition
Technical Corrigendum 2
of POSIX.1-2001
was ratified by IEEE in 2004
.RI ( IEEE\~Std\~1003.1-2001/Cor2-2004 ).
It is
.UR https:\://pubs.opengroup.org/\:onlinepubs/\:009695399/
available online
.UE .
.IP
This is informally known as
.IR POSIX.1-2004 .
.TP
.B POSIX.1-2008
.TQ
.B SUSv4
Work on the next revision of POSIX.1/SUS was completed and
ratified in 2008.
The standard is available online at
.UR http:\://www.unix.org\:/version4/
.UE ,
and also
.UR https:\://pubs.opengroup.org/\:onlinepubs/\:9699919799.2008edition/
here
.UE .
.IP
The changes in this revision are not as large as those
that occurred for POSIX.1-2001/SUSv3,
but a number of new interfaces are added
and various details of existing specifications are modified.
Many of the interfaces that were optional in
POSIX.1-2001 become mandatory in the 2008 revision of the standard.
A few interfaces that are present in POSIX.1-2001 are marked
as obsolete in POSIX.1-2008, or removed from the standard altogether.
.IP
The revised standard is structured in the same way as its predecessor.
The Single UNIX Specification version 4 (SUSv4) comprises the
Base Specifications containing XBD, XSH, XCU, and XRAT,
plus X/Open Curses Issue 7 as an extra volume that is
not in POSIX.1-2008.
.IP
Again there are two levels of conformance: the baseline
.IR "POSIX Conformance" ,
and
.IR "XSI Conformance" ,
which mandates an additional set of interfaces
beyond those in the base specification.
.IP
In general, where the STANDARDS section of a manual page
lists POSIX.1-2001, it can be assumed that the interface also
conforms to POSIX.1-2008, unless otherwise noted.
.IP
Further information can be found on the Austin Group web site,
.UR http:\://www.opengroup.org\:/austin/
.UE .
.TP
.B POSIX.1-2008 2013 edition
Technical Corrigendum 1
of POSIX.1-2008
was ratified by IEEE in 2013
.RI ( IEEE\~Std\~1003.1-2008/Cor1-2013 ).
It is
.UR https:\://pubs.opengroup.org/\:onlinepubs/\:9699919799.2013edition/
available online
.UE .
.IP
This is informally known as
.IR POSIX.1-2013 .
.TP
.B POSIX.1-2008 2016 edition
Technical Corrigendum 2
of POSIX.1-2008
was ratified by IEEE in 2016
.RI ( IEEE\~Std\~1003.1-2008/Cor2-2016 ).
It is
.UR https:\://pubs.opengroup.org/\:onlinepubs/\:9699919799.2016edition/
available online
.UE .
.TP
.B SUSv4 2016 edition
This is equivalent to POSIX.1-2008 2016 edition,
with the addition of the XCurses specification.
.TP
.B POSIX.1-2017
This revision of POSIX is technically identical to
POSIX.1-2008 2016 edition.
Ratified by IEEE in 2017
.RI ( IEEE\~Std\~1003.1-2017 ).
It is
.UR https:\://pubs.opengroup.org/\:onlinepubs/\:9699919799/
available online
.UE .
.TP
.B SUSv4 2018 edition
This is equivalent to POSIX.1-2017,
with the addition of the XCurses specification.
.TP
.B POSIX.1-2024
.TQ
.B SUSv5
Work on the next revision of POSIX.1/SUS
was completed and ratified by IEEE in 2024
.RI ( IEEE\~Std\~1003.1-2024 ).
It is
.UR https:\://pubs.opengroup.org/\:onlinepubs/\:9799919799/
available online
.UE .
.IP
POSIX.1-2024 is aligned with C17,
so that all of the library functions standardized in C17
are also standardized in POSIX.1-2024.
.IP
Further information can be found on the
.UR http:\://www.opengroup.org/\:austin/
Austin Group web site
.UE .
.P
The interfaces documented in POSIX.1/SUS are available as
manual pages under sections 0p (header files), 1p (commands),
and 3p (functions);
thus one can write
.IR man\~3p\~open .
.SS Other standards
.TP
.B LFS
The Large File Summit specification, completed in 1996.
This specification defined mechanisms that allowed 32-bit systems
to support the use of large files (i.e., 64-bit file offsets).
See
.UR https:\://www.opengroup.org\:/platform\:/lfs.html
.UE .
.SH SEE ALSO
.BR getconf (1),
.BR confstr (3),
.BR pathconf (3),
.BR sysconf (3),
.BR attributes (7),
.BR feature_test_macros (7),
.BR libc (7),
.BR posixoptions (7),
.BR system_data_types (7)
