.\" Copyright 2002, Andries E. Brouwer <aeb@cwi.nl>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH intro 1 (date) "Linux man-pages (unreleased)"
.SH NAME
intro \- introduction to user commands
.SH DESCRIPTION
Section 1 of the manual describes user commands and tools,
for example, file manipulation tools, shells, compilers,
web browsers, file and image viewers and editors, and so on.
.SH SEE ALSO
.BR intro (0)
